### ISSUE TITLE
visage-app on RHEL5  

### ISSUE THREAD

**Issue by JarleB** [auxesis/visage#47]
Hi,
first I would like to add the following additional dependendencies to the recipe for RHEL5 in order to install visage-app. 

```
yum install ruby-devel
wget http://rubyforge.org/frs/download.php/57643/rubygems-1.3.4.tgz
tar zxvf rubygems-1.3.4.tgz
cd rubygems-1.3.4
ruby setup.rb
```

then it is possible to 

```
gem install visage-app
```

However when starting it I get this ?

```
# visage-app start

_    ___
| |  / (_)________ _____ ____
| | / / / ___/ __ `/ __ `/ _ \
| |/ / (__  ) /_/ / /_/ /  __/
|___/_/____/\__,_/\__, /\___/
                 /____/

will be running at http://foo.uio.no:9292/

/usr/lib64/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/utils.rb:138:in `union': can't convert Array into String (TypeError)
    from /usr/lib64/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/utils.rb:138
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib64/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/request.rb:1
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib64/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/showexceptions.rb:3
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
     ... 9 levels...
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib64/ruby/gems/1.8/gems/visage-app-0.3.3/bin/visage-app:26
    from /usr/bin/visage-app:19:in `load'
    from /usr/bin/visage-app:19
```

**Comment by JarleB** [comment]
```
# gem list 

*** LOCAL GEMS ***

errand (0.7.2)
haml (3.0.24, 3.0.13)
rack (1.2.1)
sinatra (1.1.0, 1.0)
tilt (1.1, 1.0.1)
visage-app (0.3.3)
yajl-ruby (0.7.6)
# 
```
