### ISSUE TITLE
cucumber doesn't run, `features/data/config/default/profiles.yaml` missing

### ISSUE THREAD

**Issue by malclocke** [auxesis/visage#75]
```
$ cucumber 
No such file or directory - /home/malc/tmp/visage/features/data/config/default/profiles.yaml (Errno::ENOENT)
/usr/lib/ruby/1.8/fileutils.rb:1034:in `initialize'
/usr/lib/ruby/1.8/fileutils.rb:1034:in `open'
/usr/lib/ruby/1.8/fileutils.rb:1034:in `touch'
/usr/lib/ruby/1.8/fileutils.rb:1028:in `each'
/usr/lib/ruby/1.8/fileutils.rb:1028:in `touch'
./lib/visage-app/config/file.rb:26:in `load'
./lib/visage-app/profile.rb:15:in `load'
/home/malc/tmp/visage/lib/visage-app.rb:35
/home/malc/.gem/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:1211:in `configure'
/home/malc/tmp/visage/lib/visage-app.rb:27
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
/home/malc/tmp/visage/features/support/env.rb:15
/home/malc/.gem/ruby/1.8/gems/cucumber-1.0.0/bin/../lib/cucumber/rb_support/rb_language.rb:143:in `load'
/home/malc/.gem/ruby/1.8/gems/cucumber-1.0.0/bin/../lib/cucumber/rb_support/rb_language.rb:143:in `load_code_file'
/home/malc/.gem/ruby/1.8/gems/cucumber-1.0.0/bin/../lib/cucumber/runtime/support_code.rb:176:in `load_file'
/home/malc/.gem/ruby/1.8/gems/cucumber-1.0.0/bin/../lib/cucumber/runtime/support_code.rb:78:in `load_files!'
/home/malc/.gem/ruby/1.8/gems/cucumber-1.0.0/bin/../lib/cucumber/runtime/support_code.rb:77:in `each'
/home/malc/.gem/ruby/1.8/gems/cucumber-1.0.0/bin/../lib/cucumber/runtime/support_code.rb:77:in `load_files!'
/home/malc/.gem/ruby/1.8/gems/cucumber-1.0.0/bin/../lib/cucumber/runtime.rb:137:in `load_step_definitions'
/home/malc/.gem/ruby/1.8/gems/cucumber-1.0.0/bin/../lib/cucumber/runtime.rb:39:in `run!'
/home/malc/.gem/ruby/1.8/gems/cucumber-1.0.0/bin/../lib/cucumber/cli/main.rb:43:in `execute!'
/home/malc/.gem/ruby/1.8/gems/cucumber-1.0.0/bin/../lib/cucumber/cli/main.rb:20:in `execute'
/home/malc/.gem/ruby/1.8/gems/cucumber-1.0.0/bin/cucumber:14
/home/malc/.gem/ruby/1.8/bin/cucumber:19:in `load'
/home/malc/.gem/ruby/1.8/bin/cucumber:19
```

**Comment by auxesis** [comment]
Fixed in master.
